// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDET9BnYEHUReH4Jn7HgkMQcFKuG5jcBus',
    appId: '1:933301708273:web:6c46e16768a25af066d050',
    messagingSenderId: '933301708273',
    projectId: 'advmobprog-firebase-178d6',
    authDomain: 'advmobprog-firebase-178d6.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-178d6.firebasestorage.app',
    measurementId: 'G-DEMO123456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDET9BnYEHUReH4Jn7HgkMQcFKuG5jcBus',
    appId: '1:933301708273:android:6c46e16768a25af066d050',
    messagingSenderId: '933301708273',
    projectId: 'advmobprog-firebase-178d6',
    storageBucket: 'advmobprog-firebase-178d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDET9BnYEHUReH4Jn7HgkMQcFKuG5jcBus',
    appId: '1:933301708273:ios:6c46e16768a25af066d050',
    messagingSenderId: '933301708273',
    projectId: 'advmobprog-firebase-178d6',
    storageBucket: 'advmobprog-firebase-178d6.firebasestorage.app',
    iosBundleId: 'com.example.lab6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDET9BnYEHUReH4Jn7HgkMQcFKuG5jcBus',
    appId: '1:933301708273:ios:6c46e16768a25af066d050',
    messagingSenderId: '933301708273',
    projectId: 'advmobprog-firebase-178d6',
    storageBucket: 'advmobprog-firebase-178d6.firebasestorage.app',
    iosBundleId: 'com.example.lab6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDET9BnYEHUReH4Jn7HgkMQcFKuG5jcBus',
    appId: '1:933301708273:web:6c46e16768a25af066d050',
    messagingSenderId: '933301708273',
    projectId: 'advmobprog-firebase-178d6',
    authDomain: 'advmobprog-firebase-178d6.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-178d6.firebasestorage.app',
    measurementId: 'G-DEMO123456',
  );
}
